// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/address_provider.rs"]
pub mod address_provider;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/erc20.rs"]
pub mod erc20;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/pool_contract.rs"]
pub mod pool_contract;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/registry_contract.rs"]
pub mod registry_contract;
